//
//  XcconfigTemplate.swift
//  ezconfig
//
//  Created by Revan Ferdinand on 03/09/26.
//

import Foundation

enum XcconfigTemplate {
    
    // Base.xcconfig
    static func base(canonicalPrefix: String) -> String {
                """
                // Generated by ezconfig. File ini DI-COMMIT.
                // Jangan pernah taruh Team ID atau nilai personal di sini.
                // Nilai personal lo ada di Configs/Local.xcconfig (gitignored).
                
                #include? "Local.xcconfig"
                
                BUNDLE_PREFIX    = \(canonicalPrefix)$(LOCAL_SUFFIX)
                DEVELOPMENT_TEAM = $(LOCAL_DEV_TEAM)
                CODE_SIGN_STYLE  = Automatic
                
                """
    }
}
