//
//  XcconfigTemplate.swift
//  ezconfig
//
//  Created by Revan Ferdinand on 03/09/26.
//

import Foundation

enum XcconfigTemplate {
    
    // Base.xcconfig
    static func base(
        canonicalPrefix: String,
        appGroups: [AppGroupBinding] = []
    ) -> String {
        var text = """
        // Generated by ezconfig. File ini DI-COMMIT.
        // Jangan pernah taruh Team ID atau nilai personal di sini.
        // Nilai personal lo ada di Configs/Local.xcconfig (gitignored).
        
        #include? "Local.xcconfig"
        
        BUNDLE_PREFIX    = \(canonicalPrefix)$(LOCAL_SUFFIX)
        DEVELOPMENT_TEAM = $(LOCAL_DEV_TEAM)
        CODE_SIGN_STYLE  = Automatic
        
        """
        
        guard !appGroups.isEmpty else { return text }
        
        text += """
        
        // App Group punya variabel sendiri, bukan turunan BUNDLE_PREFIX —
        // casing-nya sering beda dari bundle ID dan harus dijaga apa adanya.
        
        """
        for g in appGroups.sorted(by: { $0.variable < $1.variable }) {
            text += "\(g.variable) = \(g.canonical)$(LOCAL_SUFFIX)\n"
        }
        return text
    }
    
    // Local.xcconfig
    static func local(teamID: String, suffix: String) -> String {
                    """
                    // Generated by ezconfig. JANGAN DI-COMMIT.
                    // File ini punya lo sendiri. Kalau kehapus, bikin ulang:
                    //   ezconfig setup
                    
                    LOCAL_DEV_TEAM = \(teamID)
                    LOCAL_SUFFIX[config=Debug] = \(suffix)
                    
                    """
    }
}
