//
//  XcconfigTemplate.swift
//  ezconfig
//
//  Created by Revan Ferdinand on 03/09/26.
//

import Foundation

enum XcconfigTemplate {
    
    // Base.xcconfig
    static func base(
        canonicalPrefix: String,
        appGroups: [AppGroupBinding] = []
    ) -> String {
        var text = """
        // Generated by ezconfig. THIS FILE IS COMMITTED.
        // Never put a Team ID or any personal value in here.
        // Your own values live in Configs/Local.xcconfig, which is gitignored.
        
        #include? "Local.xcconfig"
        
        BUNDLE_PREFIX    = \(canonicalPrefix)$(LOCAL_SUFFIX)
        DEVELOPMENT_TEAM = $(LOCAL_DEV_TEAM)
        CODE_SIGN_STYLE  = Automatic
        
        """
        
        guard !appGroups.isEmpty else { return text }
        
        text += """
        
        // App Groups get their own variable instead of deriving from
        // BUNDLE_PREFIX. Their casing often differs from the bundle ID
        // and has to be preserved exactly.
        
        """
        for g in appGroups.sorted(by: { $0.variable < $1.variable }) {
            text += "\(g.variable) = \(g.canonical)$(LOCAL_SUFFIX)\n"
        }
        return text
    }
    
    // Local.xcconfig
    static func local(teamID: String, suffix: String) -> String {
        """
        // Generated by ezconfig. DO NOT COMMIT.
        // This file is yours alone. If you lose it, recreate it with:
        //   ezconfig setup
        
        LOCAL_DEV_TEAM = \(teamID)
        LOCAL_SUFFIX[config=Debug] = \(suffix)
        
        """
    }
}
